### ISSUE TITLE
gpio21 on off

### ISSUE THREAD

**Issue by ilamparithy01** [hubbsvtgc/LearnRISC-V#3]
Hi I have seen your video I like to run gpio21on-off but i cannot see where it is , can you help me out to find it

**Comment by hubbsvtgc** [comment]
If you ask for the video/channel : https://www.youtube.com/c/LearnRISCV
However, if you ask for the blink code (turn on and off blue led using gpio) its in apps led-blink directory.

**Comment by ilamparithy01** [comment]
I like to work on interrupts , can you suggest me some interrupts based code

**Comment by hubbsvtgc** [comment]
Would this help ?

https://github.com/hubbsvtgc/LearnRISC-V/blob/release/boards/hifive1-revb/src/interrupt_vectored.S
Do you want to contribute to this repo?

**Comment by ilamparithy01** [comment]
Hi ,
Thanks for you inputs and it helped to fixe the issue in Interrupts
