### ISSUE TITLE
Switch privilege Mode M/U Riscv Vexriscv CPU with liteX

### ISSUE THREAD

**Issue by KevinQhv** [hubbsvtgc/LearnRISC-V#4]
Hi !

I try to switch privilege mode between Machine-mode and User-mode on the CPU VexRiscv with variant Secure, Linux, Full. I created a SoC with the LiteX tools. I follow your video tutorial. I realized that here :

` 

        uint32_t mstatus;
	uint32_t mepc;
	uint32_t user_entry;
	__asm__ volatile ("csrr %0, mstatus" : "=r" (mstatus));
	__asm__ volatile ("li t0, 0x8"); // set MIE bit
	__asm__ volatile ("csrs mstatus, 0x8");
	__asm__ volatile ("csrr %0, mepc" : "=r" (mepc));
	__asm__ volatile ("lw %0, %1" : "=r" (user_entry) : "m" (*enter_user_mode));
	__asm__ volatile ("csrw mepc, %0" : : "r" (user_entry));
	__asm__ volatile ("csrr t0, mstatus");
	__asm__ volatile ("li t1, 0xFFFFFFF8"); // set MPP to user mode
	__asm__ volatile ("and t0, t0, t1"); // clear MPP bits
	__asm__ volatile ("csrw mstatus, t0");
	__asm__ volatile ("mret");

`

But, i get this result in the register `mstatus`, i read with GDB  : 

`
mstatus        0x1888	SD:0 VM:00 MXR:0 PUM:0 MPRV:0 XS:0 FS:0 MPP:3 HPP:0 SPP:0 MPIE:1 HPIE:0 SPIE:0 UPIE:0 MIE:1 HIE:0 SIE:0 UIE:0
`

I have the register `mcause` to 0x11 or 0x2 but my program gets stuck on the `mret` instruction.

**Comment by hubbsvtgc** [comment]
@KevinQhv  The `MPP` (Machine previous privilege) field in `mstatus` is 3, so it would still return in machine  mode.  The `mret` command execution would take PC to the address in `mepc` register. Can you check if `mepc` register has the correct entry address?

**Comment by KevinQhv** [comment]
I did what you told me. The program sets the registers to switch from M mode to U mode. I jump well into the `enter_user_mode` function.


`
#define MASK_MPP_USER_MODE 0xFFFFE7FF

void enter_user_mode(void) {

	__asm__ volatile ("nop");
	__asm__ volatile ("nop");
	__asm__ volatile ("nop");

	__asm__ volatile ("li t0, 2");
	__asm__ volatile ("li t1, 3;");
	__asm__ volatile ("add t0, t0, t1");

	__asm__ volatile ("nop");
	__asm__ volatile ("nop");
	__asm__ volatile ("nop");
}
void main (void){

	asm volatile ("nop");
	asm volatile ("nop");
	asm volatile ("nop");

	__asm__ volatile ("li t0, 0x88"); // set MIE bit
	__asm__ volatile ("csrs mstatus, t0");
	
	void (*func_ptr)() = &enter_user_mode;  // get the function address
	register uintptr_t func_addr asm ("t0") = 0;  

	__asm__ volatile ("la %[addr], %[func]"
                  : [addr] "=r" (func_addr)
                  : [func] "i" (func_ptr));

	__asm__ volatile ("csrw mepc, t0");

	__asm__ volatile ("li t1, %0" :: "i" (MASK_MPP_USER_MODE)); // set MPP to user mode
	__asm__ volatile ("and t0, t0, t1"); // clear MPP bits
	__asm__ volatile ("csrw mstatus, t0");

	__asm__ volatile ("nop");
	__asm__ volatile ("nop");
	__asm__ volatile ("nop");

	__asm__ volatile ("mret");

	asm volatile ("nop");
	asm volatile ("nop");
	asm volatile ("nop");

	return 0;			
}
`
But I get the `mcause` register at 0x1, which gives me an exception when I enter the `enter_user_mode` function.

`
mstatus        0x80	SD:0 VM:00 MXR:0 PUM:0 MPRV:0 XS:0 FS:0 MPP:0 HPP:0 SPP:0 MPIE:1 HPIE:0 SPIE:0 UPIE:0 MIE:0 HIE:0 SIE:0 UIE:0
misa           0x40101064	RV32CFGMU
medeleg        0x40101064	1074794596
mideleg        0x40101064	1074794596
mie            0x880	2176
mtvec          0x40000020	1073741856
mcounteren     0x40000020	1073741856
mscratch       0x0	0
mepc           0x4000012c	1073742124
mcause         0x1	1
mtval          0x4000012c	1073742124
mip            0x0	0
cycle          0x1c0eff2f	470744879
time           0x1c0eff2f	470744879
instret        0x6e1af126	1847259430
cycleh         0x1f	31
timeh          0x1f	31
instreth       0x0	0
mvendorid      0x1	1
marchid        0x2	2
mimpid         0x3	3
mtohost        0x3	3
mfromhost      0x3	3
mreset         0x3	3
mipi           0x3	3
miobase        0x3	3
`

**Comment by hubbsvtgc** [comment]
@KevinQhv  Does the core have physical memory protection (PMP) support? (https://www.youtube.com/watch?v=cWlEKpCtjes)

**Comment by KevinQhv** [comment]
Yes, I want to change the privilege mode between M mode and U mode on the VexRiscv secure CPU and the CVA6 CPU variant that both support physical memory protection (PMP).

**Comment by hubbsvtgc** [comment]
Then the PMP should be configured with execution permission in U mode for the user mode code.

**Comment by KevinQhv** [comment]
even if I don't use the PMP ?

**Comment by hubbsvtgc** [comment]
Yes, disabling PMP for a region needs creating a pmp address entry with its associated address matching mode 
to be set to 00 -  PMP protection disabled.  This might help: https://www.youtube.com/watch?v=cWlEKpCtjes

**Comment by KevinQhv** [comment]
Thank you, I was able to switch to user mode and configure the PMP to accept it. Your videos are very well explained:1st_place_medal:

**Comment by Amitmaurya131** [comment]
[#define](https://www.youtube.com/hashtag/define) PMP_REG0_TOR  0x8000038C 
li x2, PMP_REG0_TOR  
  srli x2, x2, 2
  csrw pmpaddr9, x2
  li x2, 0x0e07  //read disable &  write enable
  csrw pmpcfg2, x2
  li x6, PMP_REG0_TOR
  lw x3, 0(x6)
  sw x3, 4(x6)
  sw x3, 8(x6)     
  sw x3, 16(x6)    
  in this code load stor should not happen, but its happening.
if I will take pmpcfg0 and pmpaddr1 instead of pmpcfg2 and pmpaddr9 resp. its working fine, can anyone tell solution for
