### ISSUE TITLE
How to implement in QEMU

### ISSUE THREAD

**Issue by afifahsyukri** [hubbsvtgc/LearnRISC-V#6]
I am really interested with this project as I am really new to RISC-V and trying to learn how to implement my own bootloader. May I know is there any step by step or guidance on how to use the boot program that you have developed in boards/hifive1-revb/src/start.s into QEMU? Because currently I did not purchase the board yet, however I am eager to learn how to run the code and simulate it using QEMU. I know there is a port for this board, which is sifive_e.

I really appreciate it if you can give some guidance on where to start working on this.

**Comment by hubbsvtgc** [comment]
Can you confirm if QEMU has support for hifive1-RevB board? If not, adding support in qemu for a new board is difficult and and a different task(not impossible though). Second its equally important to have gdb support to debug with qemu for hifive1-revb especially at booloader level code otherwise, it would be hard to debug.

**Comment by afifahsyukri** [comment]
Yes, I've checked through the SiFive Forum: https://forums.sifive.com/t/just-bought-a-hifive1-simulation-options-until-it-arrives/1691/3 and GitHub: https://github.com/qemu/qemu/blob/master/hw/riscv/sifive_e.c 

May I know what are the next steps to run the bootloader into machine code? Because I am quite confused on how to compile source codes

**Comment by hubbsvtgc** [comment]
@afifahsyukri "hifive1" and "hifive1-revb" board are entirely different boards.  You need to first confirm if QEMU supports **hifive1-revb** board.  If you are looking for help on **hifive1** board, I am NOT the right person, you can find information on how to build and run for hifive1 board [here](https://github.com/riscvarchive/riscv-qemu/wiki )

**Comment by hubbsvtgc** [comment]
Closing this now.
