### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [hubbsvtgc/LearnRISC-V#7]
Hello!

I found this repository from https://www.youtube.com/@LearnRISCV

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by hubbsvtgc** [comment]
HI Vazhnov, its not open to copy, change for now. However, you can use it for educational/learning purpose.

**Comment by vazhnov** [comment]
I hope one day you will release all your videos, for example, under [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) and code examples under [MIT](https://spdx.org/licenses/MIT.html) :slightly_smiling_face:
