### ISSUE TITLE
YouTube Video - How to configure physical memory protection PMP in RISC-V cpu? (https://www.youtube.com/watch?v=cWlEKpCtjes)

### ISSUE THREAD

**Issue by livid16g** [hubbsvtgc/LearnRISC-V#8]
Hello

I am looking at "slide" "Sample PMP configuration (from E51 manual)"

Now the RAM region physical address is from 0x2000_0000 to 0x2000_8000 (32 KBytes). Presumably for RV32, the Physical address is 34-bits (33:0).

Now since pmpaddrx can only hold physical address bits [33:2], we then need to right shift the above address right by two bits.

This now gives the range as 0x0800_0000 to 0x0800_2000. Since the lower address bits in pmpaddrx encode the range, then to encode a range of 32KBytes, the value that needs to be programmed in the pmpaddrx is 0x0800_1fff.

However, the "slide" shows the pmpaddrx value to be 0x0800_0fff. 

What am i missing?

Regards
JO

**Comment by hubbsvtgc** [comment]
In 0x0800_0fff, least significant zero bit position is  12 when run from zero; region Size = 2 ^ (LSZB + 3)  = 2 ^ 15 = 32 KB. Hope its clear now.

**Comment by livid16g** [comment]
Thank you for the explanaion. Now it makes sense.
